@ECHO off
call _uuid.bat ALWAYS_UP_UUID
SET ALWAYS_UP_SCRIPT_PATH=_uuid.bat
SET ALWAYS_UP_RESTART=y
SET ALWAYS_UP_RESTART_TIME=5

call _print_env.bat ALWAYS_UP

:ALWAYS_UP_LOOP
if defined ALWAYS_UP_RESTART (call _kill-after.bat %ALWAYS_UP_SCRIPT_PATH% %ALWAYS_UP_RESTART_TIME%) else (start "%ALWAYS_UP_UUID%" %ALWAYS_UP_SCRIPT_PATH%)
goto ALWAYS_UP_LOOP