@ECHO off
CALL _uuid.bat KILL_AFTER_UUID
SET KILL_AFTER_SCRIPT_PATH=%1
SET KILL_AFTER_TIMEOUT=%2

CALL _print_env.bat KILL_AFTER

start "%KILL_AFTER_UUID%" %KILL_AFTER_SCRIPT_PATH%

timeout /t %KILL_AFTER_TIMEOUT% /nobreak

CALL _kill.bat %KILL_AFTER_UUID%

SET KILL_AFTER_UUID=
SET KILL_AFTER_SCRIPT_PATH=
SET KILL_AFTER_TIMEOUT=